# -*- coding: utf-8 -*-
"""my calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MZBXEwvdT_xOTdLv-pJ7OWtXKs_-xTw_
"""

a=int(input("enter first number="))
b=int(input("enter second number="))
sum=a+b
print("sum=",sum)

from google.colab import drive
drive.mount('/content/drive')

a=int(input("enter first number="))
b=int(input("enter second number="))
sub=a-b
print("sub=",sub)

a=int(input("enter first number="))
b=int(input("enter second number="))
multiplication=a*b
print("multiplication=",multiplication)

a=int(input("enter first number="))
b=int(input("enter second number="))
division=a/b
print("division=",division)

